inheritance: true

knowledge_base:
  code_guidelines:
    filePatterns:
      - "developer-docs/**"

reviews:
  path_filters:
    - "!**/.terraform/**"
    - "!**/terraform.tfstate*"

  tools:
    checkov:
      enabled: true
    gitleaks:
      enabled: true
    golangci-lint:
      enabled: false
    hadolint:
      enabled: true
    markdownlint:
      enabled: false
    shellcheck:
      enabled: true
    tflint:
      enabled: true
    trivy:
      enabled: false
    yamllint:
      enabled: true
